### ISSUE TITLE
untyped haxe.ds.ObjectMap.getId()

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#12]
Sorry dunno how to write a title for this. This basically comes from a rather [hackish piece of code](https://github.com/MVCoconut/coconut.react-core/blob/842457e7dfa0ced5a5c52e270a82d3f0dafb0660/src/coconut/react/Key.hx#L5):

```
untyped haxe.ds.ObjectMap.getId(key)
```

This when compiled with Haxe, it is [inlined](https://github.com/HaxeFoundation/haxe/blob/4e69fda544a8a6335946538f79316ae4cb0deb26/std/js/_std/haxe/ds/ObjectMap.hx#L42) into `key.__id__`

but with genes it doesn't get inlined and remains `ObjectMap.getId`, causing runtime error because the field `getId` does not exist.

cc @back2dos

**Comment by benmerckx** [comment]
Genes is bundled with a native js map implementation (without `getId`): https://github.com/benmerckx/genes/blob/master/src/haxe/ds/ObjectMap.hx
The main reason for using the native javascript map was honestly because I didn't feel like dealing with the whole `__map_reserved` thing. There's also https://github.com/HaxeFoundation/haxe/pull/8909 which is not available in the stable releases yet but will do away with `getId`/`assignId` as well.

**Comment by kevinresol** [comment]
ok I will patch in coconut instead

**Comment by binki** [comment]
> There's also [HaxeFoundation/haxe#8909](https://github.com/HaxeFoundation/haxe/pull/8909) which is not available in the stable releases yet but will do away with `getId`/`assignId` as well.

I don’t think that PR gets rid of `getId`/`assignId`. Those functions only apply to `ObjectMap`. That PR is for `StringMap` which only supports string keys. That PR does support removing `__map_reserved` when targeting ES5. However, since `hasOwnProperty` is in ES3 I don’t get why they require ES5 for that…

`getId`/`assignId` could only be removed if targeting ES6 and reimplementing `ObjectMap` in terms of ES6 [`Map`](https://devdocs.io/javascript/global_objects/map).
