### ISSUE TITLE
Look into 9280

### ISSUE THREAD

**Issue by benmerckx** [benmerckx/genes#20]
Generate `let` and add `-D js-es=6` after this is released:
https://github.com/HaxeFoundation/haxe/pull/9280

**Comment by Antriel** [comment]
I actually got tripped by this just now, as I had `-D js-es=6`, and it worked so far, but only by a happy coincidence. Since the generated files use `var` instead of `let`, I had a situation where a variable was unintentionally shadowed.

Not a critical issue though, as I can just use ES5 and everything works.
