### ISSUE TITLE
Don't rewrite a js file if unchanged

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#21]
Otherwise it will trigger hot-reload like hell... I think it might be an opt-in

**Comment by benmerckx** [comment]
Do you use the compilation server? This should take care of that:
https://github.com/benmerckx/genes/blob/master/src/genes/Generator.hx#L133
I do have to rewrite the entry file every time since haxe clears it on every compilation.
Or are you suggesting reading out the destination file content and not writing if body equals?

**Comment by kevinresol** [comment]
argh I don't use compilation server...

**Comment by benmerckx** [comment]
Should test a little more to see if this is a sensible default, added a define for now

**Comment by benmerckx** [comment]
But, FYI, using the compilation server makes a pretty big difference after inital compile for compilation time
