### ISSUE TITLE
Guard against module statics in haxe < 4.2

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#26]
I tried to guard with `#if (haxe_ver >= 4.2)` around code that involves `KModuleFields` but seems to lead to a compiler hang (compilation never ends)

**Comment by benmerckx** [comment]
I had the same experience. But the hang seems unrelated. It happens since 12400484361ddb1bf04b76d57530ea1cc7759218.
The failure comes after upgrade of tink_unittest to latest git.
Dissected it to this commit: https://github.com/haxetink/tink_unittest/commit/30cb7cfeffd1ef1f6f92799cf793d54fd7989997
Any clues what could cause the hang?

**Comment by benmerckx** [comment]
In any case I reverted tink_unittest to last working version in 83e5c3a

**Comment by kevinresol** [comment]
Not sure about the exact cause, but I pushed a patch that seems to fix it.
