### ISSUE TITLE
main() call not emitted when --main is specified

### ISSUE THREAD

**Issue by theJenix** [benmerckx/genes#78]
When I was submitting https://github.com/benmerckx/genes/issues/77 I noticed that the code compiled with genes does not add a call to main() at the end of the the generated instancefields.js file.  When building with the default JS generator, a call to `InstanceFields.main()` is added at the bottom of the generated function.

**Comment by benmerckx** [comment]
Was this built on Windows by any chance? Genes is supposed to generate the main call to the output file (in this case -js build/instancefields.js) but that conflicts with the InstanceFields class which gets generated to build/InstanceFields.js. I assume Windows because file names are case insensitive there so this would fly under the radar.

**Comment by theJenix** [comment]
Thanks for jumping on this!  It looks like you fixed it already, but to answer your question and add context it was built on a Mac with an AFPS volume that is not case sensitive.  Just to clarify the issue, if I had properly specified the case of the output file in the build file, would that have worked?  Or would that have errored correctly because genes expects to write to an empty file?

**Comment by benmerckx** [comment]
I'm still a bit unsure :) It looks like I had a check for it at some point which was case sensitive but would fail silently. I don't think that would have been triggered here so. In any case this should fail now regardless of casing.
