### ISSUE TITLE
How to require module-level functions?

### ISSUE THREAD

**Issue by kevinresol** [benmerckx/genes#9]
In ES it is written as:
```js
import { extend } from 'react-three-fiber'
extend();
```

In Haxe:
```haxe
@:jsRequire('react-three-fiber')
extern class Utils { // just a dummy class name
	static function extend():Void;
}
```

Haxe-generated js (works):
```js
var Utils = require('react-three-fiber');
Utils.extend();
```

but genes generates (doesn't work):
```js
import Utils from 'react-three-fiber'
Utils.extend();
```

which is then translated by webpack into:

```js
react_three_fiber__WEBPACK_IMPORTED_MODULE_2__["default"].extend()
```

Note the `default` field access is invalid because the original `export` is not `default`:

```js
export function extend() {}
```

**Comment by kevinresol** [comment]
Webpack actually emits a warning:

`560:0-5 "export 'default' (imported as 'Utils') was not found in 'react-three-fiber'`

**Comment by benmerckx** [comment]
We could generate this?
````js
import * as Utils from 'react-three-fiber'
````
But then I wouldn't be quite sure how to require default. Would that be `@:jsRequire('package', 'default')` only?

**Comment by benmerckx** [comment]
Gave the above a go. It fails this test:
https://github.com/benmerckx/genes/blob/20f8b140847a2e94dc1efd2e840abdd5fb89e96b/tests/TestRequire.hx#L3

When imported as `import * as Assert from "assert"` it fail with `'Assert is not a function'`.

Because of `@:selfCall` here it actually requires a default import:
https://github.com/HaxeFoundation/hxnodejs/blob/1201320d159a583e613d3076eb00850ffeac57ca/src/js/node/Assert.hx#L56

And I realize there's more than a few instances where a default require is expected:
https://grep.app/search?q=%40%3AjsRequire%5C%28%5B%5E%5C%2C%29%5D%2A%5C%29&regexp=true

I'm thinking of either processing the class and checking if it only has statics or providing some custom metadata to generate asterisk imports.

**Comment by kevinresol** [comment]
`@:genes.wildcardImport`?

**Comment by kevinresol** [comment]
Meta is easier for the macro.

Processing the class would be easier for user. I guess the requirements are as follow (any more?)
1. `@:jsRequire` has only one argument
2. class contains only statics
3. no `@:selfCall`

**Comment by kevinresol** [comment]
How about implementing the metadata solution first so that I can continue testing on my codebase?

**Comment by benmerckx** [comment]
Yeah, I'll try it this week

**Comment by benmerckx** [comment]
I tried the "check for only statics" way.
